<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SanaaAlFarah.Business</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SanaaAlFarah.Data\SanaaAlFarah.Data.csproj" />
    <ProjectReference Include="..\SanaaAlFarah.Resources\SanaaAlFarah.Resources.csproj" />
  </ItemGroup>

</Project>
