<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SanaaAlFarah.Business\SanaaAlFarah.Business.csproj" />
    <ProjectReference Include="..\SanaaAlFarah.Data\SanaaAlFarah.Data.csproj" />
  </ItemGroup>

</Project>
